#!/bin/bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: ${0##} <username>" >&2
    echo "Example: ${0##} TwitterDev" >&2
    exit 1
fi

username=$1

if ! command -v twarc2; then
    echo "twarc2 is not installed. Installing it now..." >&2
    pip install --user -r requirements.txt
fi

dir=$(dirname "$(readlink -f "$0")")
data_dir="$dir/data/$username"
mkdir -p "$dir/data"

timeline_file="$data_dir/timeline.jsonl"

if [[ ! -f "$timeline_file" ]]; then
    if [[ -z ${BEARER_TOKEN:-} ]]; then
        echo "Environment variable BEARER_TOKEN is not defined." >&2
        exit 1
    fi
    echo "Archiving timeline..." >&2
    twarc2 --bearer-token "$BEARER_TOKEN" --verbose timeline "$username" "$timeline_file"
else
    echo "Timeline file $timeline_file already exists. Skipping scraping." >&2
fi

media_objects_file="$data_dir/media_objects.jsonl"

echo "Downloading media objects..." >&2
./download-media-objects -v "$timeline_file" "$media_objects_file"

media_files_dir="$data_dir/media"
mkdir -p "$media_files_dir"

echo "Downloading media files..." >&2
./download-media-files -v "$media_objects_file" "$media_files_dir"

echo "Done" >&2
